Greeting.create(text: 'Hello rails')
Greeting.create(text: 'Hello dear developers')
Greeting.create(text: 'Nice to hav ryou here')
Greeting.create(text: 'Lets\'s build a web app')
Greeting.create(text: 'Hi there!')